---
    - include: setup-windows.yml
      when: ansible_os_family == 'windows'
    
    - include: setup-Debian.yml
      when: ansible_os_family == 'Debian'
    
    - name: Install Filebeat.
      package: name=filebeat state=present
    
    - include: config.yml
      when: filebeat_create_config | bool
    
    - name: Ensure Filebeat is started and enabled at boot.
      service:
        name: filebeat
        state: started
        enabled: true