---
    - name: Ensure required dependencies are present.
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present
    
    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
        state: present
    
    - name: Filebeat Agent install
      shell: |
        Echo "Downloading FileBeats"
        sudo curl https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.10.2-amd64.deb --output /tmp/filebeat-oss-7.10.2-amd64.deb
        sudo apt install /tmp/filebeat-oss-7.10.2-amd64.deb
        sudo filebeat setup -e
        sudo systemctl enable filebeat
        
    - name: filebeat template
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
      notify: restart filebeat

    - name: Auditbeat Agent install
      shell: |
        Echo "Downloading AuditBeats"
        sudo curl https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-oss-7.10.2-amd64.deb --output /tmp/auditbeat-oss-7.10.2-amd64.deb
        sudo apt install /tmp/auditbeat-oss-7.10.2-amd64.deb
        sudo auditbeat setup -e
        sudo systemctl enable auditbeat
        
    - name: auditbeat template
      template:
        src: auditbeat.yml.j2
        dest: /etc/auditbeat/auditbeat.yml
      notify: restart auditbeat


    - name: Ensure Filebeat is started and enabled at boot.
      become: yes
      service:
        name: filebeat
        state: started
        enabled: true

    - name: Ensure Auditbeat is started and enabled at boot.
      become: yes
      service:
        name: auditbeat
        state: started
        enabled: true
