---
    - name: Ensure required dependencies are present.
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present
    
    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
        state: present
    
    - name: Add Filebeat repository.
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.11.1-amd64.deb/apt stable main'
        state: present
        update_cache: true
